{% set name = "picaso" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/picaso-{{ version }}.tar.gz
  sha256: c1476aff304f714d5accbc9d8b2a2f2cd8052ef2d2e93057990257944d03148b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bokeh>=2.3.0,<3.8.2
    - numpy>=2.0
    - numba
    - pandas
    - joblib
    - photutils
    - astropy-base >=3.2.3
    - matplotlib-base
    - stsynphot
    - sphinx
    - scipy
    - h5py
    - virga-exo==2.0.1
    - xarray
    - pooch
    - tqdm
    - bibtexparser==1.4.4
    - netcdf4
    - h5netcdf
    - jupytext

test:
  imports:
    - picaso
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://natashabatalha.github.io/picaso
  summary: planetary intesity code for atmospheric scattering observations
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Nicholaswogan
    - natashabatalha
